[package]
name = "hecate"
version = "0.55.0"
authors = ["ingalls <ingalls@protonmail.com>"]
license = "MIT"
description = "OpenStreetMap Inspired Data Storage Backend Focused on Performance and GeoJSON Interchange"

homepage = "https://github.com/mapbox/Hecate"
repository = "https://github.com/mapbox/Hecate"

readme = "README.md"

categories = ["database"]

[dev-dependencies]
reqwest = "0.9.5"

[dependencies]
valico = "2.3"
rand = "0.6"
postgis = "0.6.0"
protobuf = "1.5"
base64 = "0.10"
rocket = "0.4.0-rc.2"
rocket_contrib="0.4.0-rc.2"
geojson = "0.12.0"
quick-xml = "0.13.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
r2d2 = "0.8.3"
r2d2_postgres = "0.14.0"
env_logger = "0.6"


[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.postgres]
version = "0.15.2"
features = [
    "with-serde_json",
    "with-chrono"
]

[dependencies.clap]
features = ["yaml"]
version = "2.32.0"

[[bin]]
name = "hecate"
doc = false
