[package]
name = "hecate"
version = "0.1.2"
authors = ["ingalls <ingalls@protonmail.com>"]

[dependencies]
geo = "0.6.3"
iron = "0.5.1"
router = "0.5.1"
mount = "0.3.0"
geojson="0.9.0"
urlencoded = "0.5.0"
postgres = "0.15"
quick-xml = "0.9.4"
persistent = "0.3.0"
serde_json = "1.0"
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"
logger = "0.3.0"
env_logger = "0.3"

[dependencies.clap]
features = ["yaml"]
version = "2.19.0"

[[bin]]
name = "hecate"
doc = false
