[package]
name = "hecate"
version = "0.1.0"
authors = ["ingalls <ingalls@protonmail.com>"]

[dependencies]
iron = "0.5.1"
router = "0.5.1"
mount = "0.3.0"
geojson="0.9.0"
postgres = "0.15"
persistent = "0.3.0"
serde_json = "1.0"
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"

[dependencies.clap]
features = ["yaml"]
version = "2.19.0"
