[package]
name = "hecate"
version = "0.10.1"
authors = ["ingalls <ingalls@protonmail.com>"]
license = "MIT"

[dev-dependencies]
reqwest = "0.8.4"

[dependencies]
valico = "2.0"
rand = "0.4"
tempdir = "0.3"
postgis = "0.5.0"
protobuf = "^1.4"
base64 = "~0.9.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
geo = "0.6.3"
geojson = "0.9.1"
quick-xml = "0.11.0"
serde_json = "1.0"
r2d2 = "0.8.1"
r2d2_postgres = "0.14.0"
env_logger = "0.5"
fallible-iterator = "0.1.x"

[dependencies.postgres]
version = "0.15.1"
features = ["with-serde_json"]

[dependencies.clap]
features = ["yaml"]
version = "2.29.2"

[[bin]]
name = "hecate"
doc = false
