[package]
name = "hecate"
version = "0.38.1"
authors = ["ingalls <ingalls@protonmail.com>"]
license = "MIT"
description = "OpenStreetMap Inspired Data Storage Backend Focused on Performance and GeoJSON Interchange"

homepage = "https://github.com/mapbox/Hecate"
repository = "https://github.com/mapbox/Hecate"

readme = "README.md"

categories = ["database"]

[dev-dependencies]
reqwest = "0.8.4"

[dependencies]
valico = "2.1"
rand = "0.5"
postgis = "0.6.0"
protobuf = "1.5"
base64 = "0.9.2"
rocket = "0.3.11"
rocket_codegen = "0.3.11"
rocket_contrib = "0.3.11"
geojson = "0.11.0"
quick-xml = "0.12.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
r2d2 = "0.8.2"
r2d2_postgres = "0.14.0"
env_logger = "0.5"


[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.postgres]
version = "0.15.2"
features = [
    "with-serde_json",
    "with-chrono"
]

[dependencies.clap]
features = ["yaml"]
version = "2.31.2"

[[bin]]
name = "hecate"
doc = false
